services:
  db-postgres-15:
    image: postgres:15.10
    shm_size: 1g
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --address :9000 --console-address :9001
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minioadmin1
      MINIO_ROOT_PASSWORD: minioadmin1
    volumes:
      - ./.data/minio:/data
    restart: always
